# Generated by Django 4.2.7 on 2025-09-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CanadianTaxData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                (
                    "total_federal_revenue",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "gst_hst_revenue",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "income_tax_revenue",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxBracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("min_income", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "max_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("tax_rate", models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                "ordering": ["year", "min_income"],
            },
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_number", models.CharField(max_length=100, unique=True)),
                ("recipient_province", models.CharField(max_length=50)),
                ("recipient_city_en", models.CharField(max_length=100)),
                ("recipient_legal_name", models.TextField()),
                ("recipient_operating_name", models.TextField(blank=True)),
                ("recipient_type", models.CharField(max_length=10)),
                ("recipient_postal_code", models.CharField(max_length=10)),
                ("agreement_title_en", models.TextField()),
                ("agreement_number", models.CharField(max_length=100)),
                (
                    "agreement_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("description_en", models.TextField()),
                ("expected_results_en", models.TextField(blank=True)),
                ("agreement_start_date", models.DateField(blank=True, null=True)),
                ("agreement_end_date", models.DateField(blank=True, null=True)),
                ("program_name_en", models.TextField()),
                ("program_purpose_en", models.TextField(blank=True)),
                ("naics_identifier", models.CharField(blank=True, max_length=20)),
                ("naics_sector_en", models.CharField(blank=True, max_length=200)),
                ("is_notable", models.BooleanField(default=False)),
                ("is_major_funding", models.BooleanField(default=False)),
                ("notable_reason", models.TextField(blank=True)),
                ("fiscal_year", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-agreement_value", "-agreement_start_date"],
                "indexes": [
                    models.Index(
                        fields=["agreement_value"],
                        name="grants_gran_agreeme_8d6636_idx",
                    ),
                    models.Index(
                        fields=["recipient_province"],
                        name="grants_gran_recipie_0851fe_idx",
                    ),
                    models.Index(
                        fields=["fiscal_year"], name="grants_gran_fiscal__a7ddfe_idx"
                    ),
                    models.Index(
                        fields=["is_notable"], name="grants_gran_is_nota_3c06c3_idx"
                    ),
                    models.Index(
                        fields=["is_major_funding"],
                        name="grants_gran_is_majo_0bc862_idx",
                    ),
                ],
            },
        ),
    ]
