# Generated by Django 4.2.24 on 2025-09-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalAffairsGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_number", models.CharField(max_length=50, unique=True)),
                ("date_modified", models.DateField()),
                ("title", models.TextField()),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("closed", "Closed"),
                            ("terminating", "Terminating"),
                        ],
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("country", models.TextField()),
                ("region", models.CharField(blank=True, max_length=200)),
                ("locations", models.TextField(blank=True)),
                ("executing_agency_partner", models.TextField(blank=True)),
                ("contributing_organization", models.TextField(blank=True)),
                (
                    "reporting_organization",
                    models.CharField(default="Global Affairs Canada", max_length=100),
                ),
                (
                    "maximum_contribution",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("budget", models.TextField(blank=True)),
                ("program_name", models.TextField()),
                ("dac_sector", models.TextField()),
                ("aid_type", models.CharField(blank=True, max_length=100)),
                ("collaboration_type", models.CharField(blank=True, max_length=50)),
                ("finance_type", models.CharField(blank=True, max_length=100)),
                ("flow_type", models.CharField(blank=True, max_length=50)),
                ("selection_mechanism", models.CharField(blank=True, max_length=100)),
                ("expected_results", models.TextField(blank=True)),
                ("progress_and_results_achieved", models.TextField(blank=True)),
                ("policy_markers", models.TextField(blank=True)),
                ("alternate_im_position", models.CharField(blank=True, max_length=100)),
                ("other_identifier", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-maximum_contribution", "-start_date"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="grants_glob_status_ac89e6_idx"
                    ),
                    models.Index(
                        fields=["maximum_contribution"],
                        name="grants_glob_maximum_743539_idx",
                    ),
                    models.Index(
                        fields=["start_date"], name="grants_glob_start_d_c0c52e_idx"
                    ),
                    models.Index(
                        fields=["country"], name="grants_glob_country_520ded_idx"
                    ),
                    models.Index(
                        fields=["region"], name="grants_glob_region_ce8139_idx"
                    ),
                ],
            },
        ),
    ]
