# Generated by Django 4.2.24 on 2025-09-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grants", "0002_globalaffairsgrant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalaffairsgrant",
            name="aid_type",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="globalaffairsgrant",
            name="alternate_im_position",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="globalaffairsgrant",
            name="collaboration_type",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="globalaffairsgrant",
            name="finance_type",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="globalaffairsgrant",
            name="flow_type",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="globalaffairsgrant",
            name="project_number",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="globalaffairsgrant",
            name="region",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="globalaffairsgrant",
            name="reporting_organization",
            field=models.CharField(default="Global Affairs Canada", max_length=200),
        ),
        migrations.AlterField(
            model_name="globalaffairsgrant",
            name="selection_mechanism",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
