# Generated by Django 4.2.7 on 2025-09-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("annual_income", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "gst_eligible_spending",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "federal_income_tax",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("gst_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_tax_contribution",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "revenue_share_percentage",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
