# Generated by Django 4.2.7 on 2025-09-20 09:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxcalculation",
            name="grants_allocation_percentage",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("2.5"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="taxcalculation",
            name="monthly_federal_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="taxcalculation",
            name="monthly_gst_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="taxcalculation",
            name="monthly_gst_spending",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="taxcalculation",
            name="monthly_income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="taxcalculation",
            name="monthly_tax_contribution",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
