# Generated by Django 4.2.24 on 2025-09-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_taxcalculation_grants_allocation_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxcalculation",
            name="taxpayer_since_year",
            field=models.IntegerField(default=2018),
        ),
    ]
